import React, { useEffect } from 'react';
import { Link } from "react-router-dom";
import { resumeSection } from '../portfolio'
const Resume = () => {
    useEffect(() => {
        document.title = "Resume"
    }, []);
    const ResumeItems = ({ item, i }) => {
        return (
            <ul key={i}>
                <li>{item}</li>
            </ul>
        )
    }
    return (
        <>
            <section className="service-container">
                <title>Karthikeyan Portfolio | Resume </title>
                <meta name="description" content="Generated by create next app" />
                <div className="container">
                    <div className="one">
                        <span className="heading">{resumeSection.resumeheading}</span>
                    </div>
                    <div className="timeline">
                        <div className="timebar left">
                            <div className="content">
                                <span>{resumeSection.secondCompanyYear}</span>
                                {resumeSection.companies.map((item, i) => {
                                    return <ResumeItems key={i} item={item} />;
                                })}
                            </div>
                        </div>
                        <div className="timebar right">
                            <div className="content">
                                <span>{resumeSection.companiesyear}</span>
                                {resumeSection.GTS.map((item, i) => {
                                    return <ResumeItems key={i} item={item} />;
                                })}
                            </div>
                        </div>
                        <div className="timebar left">
                            <div className="content">
                                <span>{resumeSection.collegeyear}</span>
                                {resumeSection.college.map((item, i) => {
                                    return <ResumeItems key={i} item={item} />;
                                })}
                            </div>
                        </div>
                        <div className="timebar right">
                            <div className="content">
                                <span>{resumeSection.schoolyear}</span>
                                {resumeSection.school.map((item, i) => {
                                    return <ResumeItems key={i} item={item} />;
                                })}
                            </div>
                        </div>
                    </div>
                    <div className="resume-btn">
                        <Link to={resumeSection.resumepdf} target="_blank" rel="noreferrer" className="main-btn">{resumeSection.resume}</Link>
                    </div>
                </div>
            </section>
        </>
    )
}

export default Resume